import {
  IoAnalytics,
  IoBarChart,
  IoChatbubbles,
  IoClipboard,
  IoCube,
  IoPeopleCircle,
  IoPersonCircle,
  IoPrint,
  IoReceipt,
} from "react-icons/io5";
export const navigationList = [
  {
    name: "Reports",
    roles: ["manager", "admin"],
    link: "/reports",
    path: ["reports"],
    icon: IoBarChart,
  },
  {
    name: "Pos",
    roles: ["cashier"],
    link: "/pos",
    path: ["pos"],
    icon: IoPrint,
  },
  {
    name: "Profile",
    roles: ["cashier", "manager", "admin"],
    link: "/profile",
    path: ["profile"],
    icon: IoPersonCircle,
  },
  {
    name: "Products",
    roles: ["manager", "admin"],
    link: "/products",
    path: ["product"],
    icon: IoCube,
  },
  {
    name: "Inventory",
    roles: ["manager", "admin"],
    link: "/inventory",
    path: ["inventory"],
    icon: IoClipboard,
  },
  {
    name: "Receipts",
    roles: ["manager", "admin"],
    link: "/receipts",
    path: ["receipts"],
    icon: IoReceipt,
  },
  {
    name: "Accounts",
    roles: ["admin"],
    link: "/accounts",
    path: ["profile"],
    icon: IoPeopleCircle,
  },
  {
    name: "Cashier Metrics",
    roles: ["manager", "admin"],
    link: "/cashier-metrics",
    path: ["cashier-metrics"],
    icon: IoAnalytics,
  },
  // {
  //   name: "Chats",
  //   roles: ["cashier", "manager", "admin"],
  //   link: "/chats",
  //   path: "chats",
  //   icon: IoChatbubbles,
  // },
];
